In [1]:
import numpy as np

In [54]:
def power(shape = (-1,1)):
    a = list(map(int,  input().split()))
    a = np.array(a).reshape(shape)
    a = a**2
    a = np.reshape(a,shape)
    return a

In [56]:
power(shape = (2,2))

1 2 3 4


array([[ 1,  4],
       [ 9, 16]])

In [44]:
np.array([1,2,3,4]).reshape((2,2))

array([[1, 2],
       [3, 4]])

In [58]:
# Q2.
a = list(map(int, input().split()))
a = np.array(a)
n = len(a)
for i in range(len(a)):
    a[i] = a[i]**(n-i-1)
a.reshape((2,2))

2 2 2 2


array([[8, 4],
       [2, 1]])

In [71]:
a = np.array([10,20,30,40,50,60,70,80,90,100])
w = 4
n = len(a)
y = []
count = 0
for i in range(len(a)):
    if(i+w > n):
        break
    temp = a[i:i+w]
    temp = sum(temp)/w
    y.append(temp)
    count+=1

In [72]:
y

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]

In [73]:
count

7

In [82]:
def moving_average(a, w=4):
    n = len(a)
    y = []
    count = 0
    for i in range(len(a)):
        if(i+w > n):   # len(a)-w+1
            break
        temp = a[i:i+w]
        temp = sum(temp)/w
        y.append(temp)
        count+=1
    return y, count

In [84]:
a = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
y, count = moving_average(a, w=3)

In [85]:
y

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]

In [86]:
count

11